using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace System.Units.CodeGeneration.Generators
{
    internal abstract class GeneratorBase
    {
        protected readonly MyTextWriter Writer = new MyTextWriter();
        public abstract string Generate();

        public const string GeneratedFileHeader = @"//------------------------------------------------------------------------------
// <auto-generated>
//     Changes to this file will be lost when the code is regenerated.
//     The build server regenerates the code before each build and a pre-build
//     step will regenerate the code on each local build.
// </auto-generated>
//------------------------------------------------------------------------------
";
    }
}
